[package]
name = "ai"
version = "0.1.0"
authors = ["Benjamin Swerdlow <Swerdlowbenjamin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1.3"
mancala_board = "0.1.7"
rand = "0.8.3"
